### ISSUE TITLE
Support custom image-storage backend

### ISSUE THREAD

**Issue by saxbophone** [neutronX/django-markdownx#98]
It'd be great if the library could provide a way for the user to customise the loading and storing of images.

For instance, in certain cases storing media in the filesystem is not possible or advisable —in those cases, storing them in a database or an external asset-hosting service may be preferred.

Perhaps one way in which the library could do this in a loosely-coupled manner would be to allow the user to provide custom image-load and image-save functions to allow the user to write this functionality themself?

**Comment by xenatisch** [comment]
It is categorically wrong to store images or any binary data in the database. It is considered a very bad practice. 

A for the ability to store it elsewhere, you can do that right now. You can implement conditions to deal with that.

**Comment by saxbophone** [comment]
I'm aware of the bad rap that storing binary data in a database has —a bad example use case, maybe.

How are conditions for storing images elsewhere implemented? I can only see options for changing the directory that the image is stored in, however this isn't what I'm looking for. I'm looking for a way to provide a 'hook' that the library can then use for storing the images, and load them from. This could then be used for example to store them in S3 or some other asset-hosting service.

**Comment by xenatisch** [comment]
That's not flexibility, that's enabling a bad practice. I cannot think of a reason why would someone want to save images in the database, especially when these images are obtained from a text editor. This is just a recipe for disaster. So I am against it unless I hear specific, valid arguments to convince me otherwise.

As for the `MEDIA`, you can set your media directory on S3, or use multiple embedded Django projects to handle different needs. Otherwise, you can inherit `forms.ImageForm` , change it, and use it to save the contents in a specific widget. 

On that point, we can probably make this slightly easier by allow the use of a function as well as a string for names. So, that's something we can work on.

**Comment by saxbophone** [comment]
I personally feel that the principle of separation of concerns means that this project shouldn't worry about where the files are being stored —allowing for things to be generic can allow people to do bad things (I appreciate your aversion to storing binary data in DBs comes from a place of wisdom), but also allows for the freedom, flexibility and extensibility to do good things, possibly more suited to a specific project or custom solution.

Regarding S3, I considered changing the `MEDIA` path to an S3 endpoint, however I don't think this would support uploads so it might instead require changing the whole default django storage backend to one using S3, or another service.

In any case, I am going to do some experimentation in a fork with adding a feature providing the ability for the file storage backend used by the library to be customised, possibly also adding some customisation of the file names.

I appreciate you're a bit averse to my suggestions given the context so I will do some work on this in a fork for now.

**Comment by adi-** [comment]
Have you tried to use https://github.com/jschneier/django-storages ?

**Comment by saxbophone** [comment]
@adi- thanks, that looks like that will do nicely —can't believe I missed this!
